### PR TITLE
315/user mgmt add edit user

### PR DESCRIPTION
**Pull request by ssaegrov**
**Please check if the PR fulfills these requirements**

- [ ] The code builds and tests pass (verified by our automated build checks)
- [ ] Commit messages follow this format
```
    Summary of the changes
    - Detail 1
    - Detail 2

    Fixes #issuenumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Code meets the expectations our engineering guidelines. https://github.com/aspnet/Home/wiki/Engineering-guidelines.

Please review the guidelines for CONTRIBUTING.md for more details.

### CODE REVIEW

**Comment by jorgenfar** [comment]
@Velcrow81 I'll take a look at it tonight.

**Comment by Velcrow81** [comment]
Seems build is still failing. Nearly there :)

**Comment by jorgenfar** [comment]
I'm still making some changes, and I also think I'm going to squash everything together to get rid of the noise in the git log. I'll ping you when I'm finished and this is ready for review again. :-)

**Comment by jorgenfar** [comment]
@Velcrow81 All right, this should be ready now. 

it seems squashing everything together into a pretty little commit wasn't the smartest thing to do, because I forgot the previous merge from master into this branch had been done using a merge and not a rebase. Anyway, I've reverted my squash now, and we'll just have to live with this PR introducing noise into the git log.

I'm planning to sit down tomorrow and create some issues for further work, including DRYing up the forms (e.g., by creating components representing the different input fields that can be reused), some styling changes, displaying validation from the back-end, and so on.

**Comment by Velcrow81** [comment]
Good job!

**Pull request merged**
