### PR TITLE
Issue 644: Add RegisteredBy information to DataCollector classes in backend

### PR DESCRIPTION
**Pull request by cathinkaw**
https://github.com/IFRCGo/cbs/issues/644

@einari could you or anyone else at Dolittle help out with implementing fetching the users guid from the login information? We weren't able to do this as the login is mocked in dev.

In our opinion the fetching of the user information should be done backend.

PS. Please correct our code if we have added RegisteredBy in too many places. We weren't to sure about where it was needed.

### CODE REVIEW

**Comment by einari** [comment]
I have a couple of questions:

- Is this for audit trails? The issue seems very technical, what is it going to be used for?
- Is there a relationship between a CBS concept and the user? e.g. DataOwner ? 

The oid that sits on for instance the JWT token coming back is going to be the oid coming from the actual provider. There is no guarantee that this will be a GUID - as different providers have different unique identifiers. In addition to this, in the future the users could be sourced from multiple places. In the federated gateway that Dolittle provides, we will be keeping a GUID to identify them - but I do suspect we probably don't want that coupling.

**Comment by cathinkaw** [comment]
@karolikl or @aninek can you answer Einar's questions?

**Comment by aninek** [comment]
Data collectors should be registered by 'their' data verifiers, so knowing 'registered by' means we know the hierarchy of the CBS design.

**Comment by einari** [comment]
Would it then be fair to say that Data Verifier should be formalized as a concept and with it there is associated an identity and then it becomes the DataVerifier we want to know about. 

From what I can read then is that you're not really that interested in the "RegisteredBy" but more who the data collector belongs to? This is just a convention you'll put in place.  If so, wouldn't be better then to call it "OwnedBy" ?  Or something that refers to the relationship, rather than registered - as that sounds like an auditing concern.

**Comment by eprom** [comment]
@einari I am with you on inconsistent id's coming from  a different identity providers. We do expect a token that the CBS services consume after a user is successfully authenticated. The token should contain a user id and a role that is consistent across the services. Since we are re-signing the token after a user authenticated by IDP, is there any challenge making a consistent user id available to the CBS services? I am aware of we are not there yet on the authorisation :-)

**Comment by cathinkaw** [comment]
It has been decided that what is interesting is the responsible data verifier (https://github.com/IFRCGo/cbs/pull/819). This PR is therefore no longer relevant.

**Pull request closed without merging**
