### PR TITLE
Fake json data for analytics

### PR DESCRIPTION
**Pull request by raubreywhite**
I've included fake json data for prototyping the analytics D3 graphs.

### CODE REVIEW

**Comment by alexanderhoset** [comment]
Why is this failing even if it is only static files added. 

@jakhog are you looking at it?  

can be related to dolittle latest packages?

**Comment by raubreywhite** [comment]
I just merged in all the latest updates other people have done...

**Comment by alexanderhoset** [comment]
I am checking this, but waiting to merge until @jakhog is done with the review and merge of the total dolittle refactor to get a working master (#884)

**Comment by karolikl** [comment]
@alexanderhoset, PR #884 has been merged, could you follow up on this one?

**Comment by raubreywhite** [comment]
Ok, the compiled JS code should be removed now.

**Pull request merged**
