### PR TITLE
Issues/npm build issues

### PR DESCRIPTION
**Pull request by beatfactor**
Fixed NPM install issues in VolunteerReporting and Admin bounded contexts.

### CODE REVIEW

**Comment by karolikl** [comment]
I tried this on Windows running npm install in Source/VolunteerReporting/Web.Frontend and I received the following error: 

'cp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ifrc-cbs/common-react-ui@0.0.2 export: `babel src --verbose --out-dir es && cp -R src/assets es`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ifrc-cbs/common-react-ui@0.0.2 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\karolikl\AppData\Roaming\npm-cache\_logs\2019-01-19T08_45_48_057Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ifrc-cbs/common-react-ui@0.0.2 prepare: `npm run clean && npm run export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ifrc-cbs/common-react-ui@0.0.2 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\karolikl\AppData\Roaming\npm-cache\_logs\2019-01-19T08_45_48_122Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ifrc-cbs/reporting@0.0.4 preinstall: `cd ../../Navigation/Web.Common && npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ifrc-cbs/reporting@0.0.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\karolikl\AppData\Roaming\npm-cache\_logs\2019-01-19T08_45_48_232Z-debug.log

**Comment by karolikl** [comment]
Same error in Source/Admin/Web.Frontend

**Comment by beatfactor** [comment]
Yeah, there is no `cp` in `cmd`, but it works in Powershell?

**Comment by karolikl** [comment]
Unfortunately not, I get the same error in PowerShell

**Pull request closed without merging**
