### PR TITLE
Adds structured logging and logging infrastructure (plus start of Kafka infra)

### PR DESCRIPTION
**Pull request by einari**
This is related to #385 

**Please check if the PR fulfills these requirements**

- [ ] The code builds and tests pass (verified by our automated build checks)
- [ ] Commit messages follow this format
```
    Summary of the changes
    - Detail 1
    - Detail 2

    Fixes #issuenumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Code meets the expectations our engineering guidelines. https://github.com/aspnet/Home/wiki/Engineering-guidelines.

Please review the guidelines for CONTRIBUTING.md for more details.

### CODE REVIEW

**Comment by einari** [comment]
Which project failed worth this?
I tried a couple before pushing, apparently not the right one.

**Comment by karolikl** [comment]
Pull down the following images, and you will see the error: 

karolikl/cbs-vr-backend:1218
karolikl/cbs-admin-backend:1219
karolikl/cbs-usermgmt-backend:1220

The error message included in #392 was locally, when trying to run Admin.

**Comment by einari** [comment]
Thanks. Come to think of it. I only runtime tested the Example app but compiled all. Which might be proving a difference in these projects. Will have a look and see what the difference is as well.

**Comment by einari** [comment]
This is slightly weird. I've run all your images and they run fine on my machine. I've also run it manually with "dotnet run" - works fine.  I'm going to push again. 
The error you had refers to Kestrel falling over. Which is a very strange thing seeing that this is just configuring a specific Log Provider for Serilog.

**Pull request merged**
