### PR TITLE
Add navigation bar to admin

### PR DESCRIPTION
**Pull request by Virrum**
** Navigation bar added to Admin **
This is a working sample on how to use the navigation bar in an iframe. This way we can test how it works with authentication. nudge @einari, @eprom  and @beatfactor .

### CODE REVIEW

**Comment by beatfactor** [comment]
@Virrum Cool. Could you share the steps on how to build and run the iframe enabled app locally please?

**Comment by Virrum** [comment]
Yes.
In folder: `./Source/Navigation/Web/`
`$ npm install`
`$ npm start`
This will run and open automatically http://localhost:9999

In folder: `./Source/Admin/Web.Angular`
`$ npm install`
`$ ng serve --watch`
This will enable http://localhost:4200 (you need to open a browser tab manually on this)

Now you can do changes to navigation and see it automatically updates in the admin app.
You can also stop the navigation service and see how the admin behaves. This is pure beauty of bounded contexts :)
 bitmoji

**Comment by alexanderhoset** [comment]
Looks good!

**Comment by alexanderhoset** [comment]
I will fix the docs @Velcrow81

**Comment by Virrum** [comment]
Thanks! Sorry for the lack of documentation bitmoji

**Pull request merged**
