### PR TITLE
Make Testdata generator simpler and more flexible

### PR DESCRIPTION
**Pull request by woksin**
Should close down issues: #479, #500 

Made the Web project dependent on Domain.Specs, the though is that the testdata generator should have access to the specs of the domain to be able to always generate correct data according to the specs.

Also, should methods in the Read collections really throw exception, for example when a user with a specific ID is not found?

### CODE REVIEW

**Comment by einari** [comment]
The Web project shouldn't be dependant on the Specs project - but rather if there is something that we want to share between them, put it in a third one. 
 
As for exceptions - in general a rule of thumb; exceptions are to be considered an exceptional non-recoverable state and something we should avoid being in. If a query can't find any results, it shouldn't throw an exception - but rather an empty collection.

**Comment by woksin** [comment]
@einari I see. I'll change that then, I was wondering if this was okay so thanks for the feedback.

And for the exceptions, so returning null instead is preferred over exceptions?

**Comment by einari** [comment]
Great. 

Returning null is probably not a good idea - null is evil :)

But if it's supposed to return a collection, return an empty one.

If it is returning a single instance and it is wrong there is something missing to validate before you get to the place where you're supposed to return this. 
We (Dolittle) have specific return types for the different pipelines.

**Comment by einari** [comment]
https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare

**Comment by woksin** [comment]
I've read it :wink: I've got mixed feelings, but what do I know...

**Comment by einari** [comment]
What is missing is a semantically correct response. For instance what we return is a CommandResult and a QueryResult object for the different pipelines and it contains broken rules avoiding it all together. Sometimes there are exceptions - but then theee is a good reason

**Comment by woksin** [comment]
I agree with you there, how we're actually going to implement this is a theme for discussion for code eve I think

**Comment by woksin** [comment]
I'm thinking of removing the "test stuff" from the Web-project entirely and putting it in its own project

**Pull request merged**
