### PR TITLE
315/rix1/upgrade dependencies

### PR DESCRIPTION
**Pull request by rix1**
Upgraded a couple of PATCH and MINOR dependencies: 

- `Zone.js`
- `core-js`
- `typescript`, `@angular/cli` and `rxjs`

### CODE REVIEW

**Comment by rix1** [comment]
Note: I wasn't able to run the tests. Will update PR when I get them up and running.

**Comment by karolikl** [comment]
Would you like me to wait with merging the PR until you've had a look at the tests?

**Comment by rix1** [comment]
Yes, please wait :) I'll take a look at it this weekend.

**Comment by karolikl** [comment]
Closing as this is part of #422

**Pull request closed without merging**
