### PR TITLE
Remove Linux Docker image.

### PR DESCRIPTION
**Pull request by sheeeng**
Clean up the Linux image, which is not taken into use.

### CODE REVIEW

**Comment by sheeeng** [comment]
I see that CBS enable TravisCI already.
I will remove `.travis.yml` file since it is not used at the moment.
Should we continue to support the Linux image?

**Comment by Velcrow81** [comment]
Please commit a dummy request or merge in latest to trigger new build. There was a build error before that has been fixed

**Comment by sheeeng** [comment]
I got the impression earlier that we are not using TravisCI anymore, but focusing only on using AppVeyor?

**Comment by Velcrow81** [comment]
I am not familiar with this. I think we need both to cover Linux and Windows. Any input @karolikl ?

**Comment by einari** [comment]
Kubernetes is running on Linux and all containers are based on that - so it would be nice to have it confirmed running on Linux. AppVeyor is bringing out Linux support however - so maybe we could migrate over to it? Read more [here](https://www.appveyor.com/beta/).

**Comment by sheeeng** [comment]
Thanks for the clarification.

**Pull request closed without merging**
