### PR TITLE
Rewrote Excel-export in Reporting with ClosedXML and removed OpenDocument-XML.

### LINKED ISSUE #676: Change datatype of timestamp in export to excel
Change the datatype to datatime / datetimeoffset

### LINKED ISSUE #736: Change date formatting in export of volunteer reporting
When the timestamp (date) is exported to excel it takes the form "year, month (in letters), date". However, it would be useful if it was exported as dd.mm.yy (numerically) to allow for manual data analysis.

### LINKED ISSUE #824: Error when exporting Volunteer Report to excel
### Description
When exporting the report to excel the user receives an error-message:
image

When clicking "Yes" you will get the data, but we dont know if it is correct.

### PR DESCRIPTION
**Pull request by esp0**
Rewrote excel-export with ClosedXML and removed OpenDocument-XML.

Fixes #736
Fixes #676
Fixes #824

### CODE REVIEW

**Comment by karolikl** [comment]
@woksin, have you had the chance to test this?

**Comment by woksin** [comment]
I think that we kinda need #971 to test this properly, I remember @esp0 started on work on the last code evening

**Comment by jakhog** [comment]
Didn't we make som progress on this at the code-evening @esp0? Feel free to let me know if there are still something missing to get it working

**Comment by esp0** [comment]
I have created a draft pull request (#985) to fix #971 . I have however not been able to test the changes because all efforts to insert test data have failed.

**Comment by jakhog** [comment]
Unfortunately ClosedXML didn't play nice with our Docker images, as it had some dependencies on third party binaries. Did the same changes in #1000 but with EPPlus which seems to work nicely, and has a simple API like this one.

**Pull request closed without merging**
