### PR TITLE
Column name fix #1110

### LINKED ISSUE #1110: change title of "total people" column to "total"
The total column in the excel export now says "total persons". Need to be "total" only.

### PR DESCRIPTION
**Pull request by praktikon**
This Fixes #1110

### CODE REVIEW

**Comment by gardnk** [comment]
Why is this closed @praktikon ? Looks to me like an easy fix, I would merge it 🙃

**Comment by praktikon** [comment]
There were some check problems, but it's look like they are gone now ¯\_(ツ)_/¯ .
So, if everything is Ok, feel free to merge 🙃

**Comment by praktikon** [comment]
Checks have failed all the same😟
 I don't know how to address this issue.
(Locally on my machine, everything builds without errors and works fine.)

Here is an excerpt from build log (https://cbsrc.visualstudio.com/cbs/_build/results?buildId=731)

image

**Comment by gardnk** [comment]
Ok, it builds locally for me as well. This also happened for another PR that builds and runs fine locally. I will look into this

**Comment by esp0** [comment]
Closes #1110

**Pull request merged**
