### PR TITLE
F add user in modal

### PR DESCRIPTION
**Pull request by cathinkaw**
Started the work to remove Material and also start getting the add user part of the solution in a modal.

Should resolve:
https://github.com/IFRCGo/cbs/issues/352

And is also linked to:
https://github.com/IFRCGo/cbs/issues/350

Sorry about the partly finished rewrite. But I think it is better to get this merged in, than not.

### CODE REVIEW

**Comment by cathinkaw** [comment]
It fails because I have only partially removed code. I will clean up this as soon as I can!

**Comment by cathinkaw** [comment]
I have now removed the outcommented code that was blocking one of the tests. This now also includes the list of users. Sorry about the big PR and not fixing it sooner :)

**Comment by cathinkaw** [comment]
Thanks! :)

Can I merge, or should one of the core team merge?

**Comment by alexanderhoset** [comment]
done

**Pull request merged**
