### PR TITLE
Rix1/upgrade dependencies

### LINKED ISSUE #315: Upgrade handlebars.js in Admin project
### Description
handlebars.js version 1.3.0 has a known security vulnerability. Upgrade to newest version.

### PR DESCRIPTION
**Pull request by rix1**
Summary of the changes
- Upgraded `angular-cli`, `rxjs` and `zone.js`
- Add missing dev-dependencies and config files for getting tests up and running locally (with `ng test`

Fixes #315

### CODE REVIEW

**Comment by Velcrow81** [comment]
Both builds are failing. Fix and try again :)

**Comment by rix1** [comment]
@Velcrow81 Will do! I've experienced some issues with `npm` on this branch. Works fine when installing dependencies with `yarn`, so I'm thinking there might be some issues with the `package-lock.json` file.

**Comment by Velcrow81** [comment]
Any progress on this @rix1 ?

**Comment by Velcrow81** [comment]
@rix1: Do you need help with this?

**Comment by rix1** [comment]
Welp – This got really messy. I removed the tests on a clean branch and pushed to #509. Closing this one.

**Pull request closed without merging**
