### PR TITLE
Created SharedModule, added hashing for routes, created check for CoreModule, created an ApiService that uses Observables instead of Promises

### PR DESCRIPTION
**Pull request by mathisGarberg**
**Please check if the PR fulfills these requirements**

- [ ] The code builds and tests pass (verified by our automated build checks)
- [ ] Commit messages follow this format
```
    Summary of the changes
    - Detail 1
    - Detail 2

    Fixes #issuenumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Code meets the expectations our engineering guidelines. https://github.com/aspnet/Home/wiki/Engineering-guidelines.

Please review the guidelines for CONTRIBUTING.md for more details.

### CODE REVIEW

**Comment by mathisGarberg** [comment]
Will do

**Comment by alexanderhoset** [comment]
is there any reason you need node-sass when we use angular-cli  ?

**Comment by mathisGarberg** [comment]
When I first ran the project, node-sass was listed as a required dependency. The project simply woudn’t function without it. I cab hovewer remove it from the dependency list.

**Comment by alexanderhoset** [comment]
I vote for removal if it can run without it

**Comment by karolikl** [comment]
Looks great, thanks!

**Pull request merged**
